import { Power0 } from "gsap";

const resource = [
	{ name: "scence_2", url: "./assets/secreen_2.png" },
	{ name: "scence_3", url: "./assets/secreen_3.png" },
	{ name: "scence_4", url: "./assets/secreen_4.png" },
	{ name: "scence_5", url: "./assets/secreen_5.png" },
	{ name: "scence_6", url: "./assets/secreen_6.png" },
	{ name: "scence_7", url: "./assets/secreen_7.png" },
	{ name: "bike1", url: "./assets/bike/s_3_bike1.png" },
	{ name: "bike2", url: "./assets/bike/s_3_bike2.png" },
	{ name: "bike3", url: "./assets/bike/s_3_bike3.png" },
	{ name: "bike4", url: "./assets/bike/s_3_bike4.png" },
	{ name: "bike5", url: "./assets/bike/s_3_bike5.png" },
	{ name: "bike6", url: "./assets/bike/s_3_bike6.png" },
	{ name: "bike7", url: "./assets/bike/s_3_bike7.png" },
	{ name: "bike8", url: "./assets/bike/s_3_bike8.png" },
	{ name: "bike9", url: "./assets/bike/s_3_bike9.png" },
	{ name: "bike10", url: "./assets/bike/s_3_bike10.png" },
	{ name: "bike11", url: "./assets/bike/s_3_bike11.png" },
	{ name: "bike12", url: "./assets/bike/s_3_bike12.png" },
	{ name: "bike13", url: "./assets/bike/s_3_bike13.png" },
	{ name: "bike14", url: "./assets/bike/s_3_bike14.png" },
	{ name: "bike15", url: "./assets/bike/s_3_bike15.png" },
	{ name: "bike16", url: "./assets/bike/s_3_bike16.png" },
	{ name: "bike17", url: "./assets/bike/s_3_bike17.png" },
	{ name: "bike18", url: "./assets/bike/s_3_bike18.png" },
	{ name: "bike19", url: "./assets/bike/s_3_bike19.png" },
	{ name: "bike20", url: "./assets/bike/s_3_bike20.png" },
	{ name: "dialog3", url: "./assets/s_3_dialog.png" },
	{ name: "car", url: "./assets/s_6_car.png" },
	{ name: "win", url: "./assets/s_6_win.png" },
	{ name: "win_right", url: "./assets/s_6_win_right.png" },
	{ name: "s_6_cloud", url: "./assets/s_6_cloud.png" },
	{ name: "dialog6", url: "./assets/s_6_dialog.png" },
	{ name: "bear", url: "./assets/s_2_bear.png" },
	{ name: "dialog2", url: "./assets/s_2_dialog.png" },
	{ name: "tip01", url: "./assets/s_1_tip.png" },
	{ name: "s_2_tree", url: "./assets/s_2_tree.png" },
	{ name: "s_2_flower_1", url: "./assets/s_2_flower/1.png" },
	{ name: "s_2_flower_2", url: "./assets/s_2_flower/2.png" },
	{ name: "s_2_flower_3", url: "./assets/s_2_flower/3.png" },
	{ name: "s_2_flower_4", url: "./assets/s_2_flower/4.png" },
	{ name: "s_2_flower_5", url: "./assets/s_2_flower/5.png" },
	{ name: "s_2_flower_6", url: "./assets/s_2_flower/6.png" },
	{ name: "s_2_flower_7", url: "./assets/s_2_flower/7.png" },
	{ name: "s_2_flower_8", url: "./assets/s_2_flower/8.png" },
	{ name: "s_2_flower_9", url: "./assets/s_2_flower/9.png" },
	{ name: "s_2_flower_10", url: "./assets/s_2_flower/10.png" },
	{ name: "s_2_flower_11", url: "./assets/s_2_flower/11.png" },
	{ name: "s_2_flower_12", url: "./assets/s_2_flower/12.png" },
	{ name: "s_2_flower_13", url: "./assets/s_2_flower/13.png" },
	{ name: "s_2_flower_14", url: "./assets/s_2_flower/14.png" },
	{ name: "s_2_flower_15", url: "./assets/s_2_flower/15.png" },
	{ name: "s_2_flower_16", url: "./assets/s_2_flower/16.png" },
	{ name: "s_2_flower_17", url: "./assets/s_2_flower/17.png" },
	{ name: "s_2_flower_18", url: "./assets/s_2_flower/18.png" },
	{ name: "s_2_flower_19", url: "./assets/s_2_flower/19.png" },
	{ name: "s_2_flower_20", url: "./assets/s_2_flower/20.png" },
	{ name: "s_2_flower_21", url: "./assets/s_2_flower/21.png" },
	{ name: "s_2_flower_22", url: "./assets/s_2_flower/22.png" },
	{ name: "s_2_flower_23", url: "./assets/s_2_flower/23.png" },
	{ name: "s_2_flower_24", url: "./assets/s_2_flower/24.png" },
	{ name: "s_2_flower_25", url: "./assets/s_2_flower/25.png" },
	{ name: "s_2_2_flower_1", url: "./assets/s_2_flower_2/1.png" },
	{ name: "s_2_2_flower_2", url: "./assets/s_2_flower_2/2.png" },
	{ name: "s_2_2_flower_3", url: "./assets/s_2_flower_2/3.png" },
	{ name: "s_2_2_flower_4", url: "./assets/s_2_flower_2/4.png" },
	{ name: "s_2_2_flower_5", url: "./assets/s_2_flower_2/5.png" },
	{ name: "s_2_2_flower_6", url: "./assets/s_2_flower_2/6.png" },
	{ name: "s_2_2_flower_7", url: "./assets/s_2_flower_2/7.png" },
	{ name: "s_2_2_flower_8", url: "./assets/s_2_flower_2/8.png" },
	{ name: "s_2_2_flower_9", url: "./assets/s_2_flower_2/9.png" },
	{ name: "s_2_2_flower_10", url: "./assets/s_2_flower_2/10.png" },
	{ name: "s_2_2_flower_11", url: "./assets/s_2_flower_2/11.png" },
	{ name: "s_2_2_flower_12", url: "./assets/s_2_flower_2/12.png" },
	{ name: "s_2_2_flower_13", url: "./assets/s_2_flower_2/13.png" },
	{ name: "s_2_2_flower_14", url: "./assets/s_2_flower_2/14.png" },
	{ name: "s_2_2_flower_15", url: "./assets/s_2_flower_2/15.png" },
	{ name: "s_2_2_flower_16", url: "./assets/s_2_flower_2/16.png" },
	{ name: "s_2_2_flower_17", url: "./assets/s_2_flower_2/17.png" },
	{ name: "s_2_2_flower_18", url: "./assets/s_2_flower_2/18.png" },
	{ name: "s_2_2_flower_19", url: "./assets/s_2_flower_2/19.png" },
	{ name: "s_2_2_flower_20", url: "./assets/s_2_flower_2/20.png" },
	{ name: "s_2_2_flower_21", url: "./assets/s_2_flower_2/21.png" },
	{ name: "s_2_2_flower_22", url: "./assets/s_2_flower_2/22.png" },
	{ name: "s_2_2_flower_23", url: "./assets/s_2_flower_2/23.png" },
	{ name: "s_2_2_flower_24", url: "./assets/s_2_flower_2/24.png" },
	{ name: "s_2_2_flower_25", url: "./assets/s_2_flower_2/25.png" },
	{ name: "s_2_cloud", url: "./assets/s_2_cloud.png" },
	{ name: "s_3_flower_1", url: "./assets/s_3_flower/1.png" },
	{ name: "s_3_flower_2", url: "./assets/s_3_flower/2.png" },
	{ name: "s_3_flower_3", url: "./assets/s_3_flower/3.png" },
	{ name: "s_3_flower_4", url: "./assets/s_3_flower/4.png" },
	{ name: "s_3_flower_5", url: "./assets/s_3_flower/5.png" },
	{ name: "s_3_flower_6", url: "./assets/s_3_flower/6.png" },
	{ name: "s_3_flower_7", url: "./assets/s_3_flower/7.png" },
	{ name: "s_3_flower_8", url: "./assets/s_3_flower/8.png" },
	{ name: "s_3_flower_9", url: "./assets/s_3_flower/9.png" },
	{ name: "s_3_flower_10", url: "./assets/s_3_flower/10.png" },
	{ name: "s_3_flower_11", url: "./assets/s_3_flower/11.png" },
	{ name: "s_3_flower_12", url: "./assets/s_3_flower/12.png" },
	{ name: "s_3_flower_13", url: "./assets/s_3_flower/13.png" },
	{ name: "s_3_flower_14", url: "./assets/s_3_flower/14.png" },
	{ name: "s_3_flower_15", url: "./assets/s_3_flower/15.png" },
	{ name: "s_3_flower_16", url: "./assets/s_3_flower/16.png" },
	{ name: "s_3_flower_17", url: "./assets/s_3_flower/17.png" },
	{ name: "s_3_flower_18", url: "./assets/s_3_flower/18.png" },
	{ name: "s_3_flower_19", url: "./assets/s_3_flower/19.png" },
	{ name: "s_3_flower_20", url: "./assets/s_3_flower/20.png" },
	{ name: "s_3_flower_21", url: "./assets/s_3_flower/21.png" },
	{ name: "s_3_flower_22", url: "./assets/s_3_flower/22.png" },
	{ name: "s_3_flower_23", url: "./assets/s_3_flower/23.png" },
	{ name: "s_3_flower_24", url: "./assets/s_3_flower/24.png" },
	{ name: "s_3_flower_25", url: "./assets/s_3_flower/25.png" },
	{ name: "s_3_2_flower_1", url: "./assets/s_3_flower_2/1.png" },
	{ name: "s_3_2_flower_2", url: "./assets/s_3_flower_2/2.png" },
	{ name: "s_3_2_flower_3", url: "./assets/s_3_flower_2/3.png" },
	{ name: "s_3_2_flower_4", url: "./assets/s_3_flower_2/4.png" },
	{ name: "s_3_2_flower_5", url: "./assets/s_3_flower_2/5.png" },
	{ name: "s_3_2_flower_6", url: "./assets/s_3_flower_2/6.png" },
	{ name: "s_3_2_flower_7", url: "./assets/s_3_flower_2/7.png" },
	{ name: "s_3_2_flower_8", url: "./assets/s_3_flower_2/8.png" },
	{ name: "s_3_2_flower_9", url: "./assets/s_3_flower_2/9.png" },
	{ name: "s_3_2_flower_10", url: "./assets/s_3_flower_2/10.png" },
	{ name: "s_3_2_flower_11", url: "./assets/s_3_flower_2/11.png" },
	{ name: "s_3_2_flower_12", url: "./assets/s_3_flower_2/12.png" },
	{ name: "s_3_2_flower_13", url: "./assets/s_3_flower_2/13.png" },
	{ name: "s_3_2_flower_14", url: "./assets/s_3_flower_2/14.png" },
	{ name: "s_3_2_flower_15", url: "./assets/s_3_flower_2/15.png" },
	{ name: "s_3_2_flower_16", url: "./assets/s_3_flower_2/16.png" },
	{ name: "s_3_2_flower_17", url: "./assets/s_3_flower_2/17.png" },
	{ name: "s_3_2_flower_18", url: "./assets/s_3_flower_2/18.png" },
	{ name: "s_3_2_flower_19", url: "./assets/s_3_flower_2/19.png" },
	{ name: "s_3_2_flower_20", url: "./assets/s_3_flower_2/20.png" },
	{ name: "s_3_2_flower_21", url: "./assets/s_3_flower_2/21.png" },
	{ name: "s_3_2_flower_22", url: "./assets/s_3_flower_2/22.png" },
	{ name: "s_3_2_flower_23", url: "./assets/s_3_flower_2/23.png" },
	{ name: "s_3_2_flower_24", url: "./assets/s_3_flower_2/24.png" },
	{ name: "s_3_2_flower_25", url: "./assets/s_3_flower_2/25.png" },
	{ name: "s_3_tree", url: "./assets/s_3_tree.png" },
	{ name: "s_4_flower_10", url: "./assets/s_4_flower/10.png" },
	{ name: "s_4_flower_11", url: "./assets/s_4_flower/11.png" },
	{ name: "s_4_flower_12", url: "./assets/s_4_flower/12.png" },
	{ name: "s_4_flower_13", url: "./assets/s_4_flower/13.png" },
	{ name: "s_4_flower_14", url: "./assets/s_4_flower/14.png" },
	{ name: "s_4_flower_15", url: "./assets/s_4_flower/15.png" },
	{ name: "s_4_flower_16", url: "./assets/s_4_flower/16.png" },
	{ name: "s_4_flower_17", url: "./assets/s_4_flower/17.png" },
	{ name: "s_4_flower_18", url: "./assets/s_4_flower/18.png" },
	{ name: "s_4_flower_19", url: "./assets/s_4_flower/19.png" },
	{ name: "s_4_flower_20", url: "./assets/s_4_flower/20.png" },
	{ name: "s_4_flower_21", url: "./assets/s_4_flower/21.png" },
	{ name: "s_4_flower_22", url: "./assets/s_4_flower/22.png" },
	{ name: "s_4_flower_23", url: "./assets/s_4_flower/23.png" },
	{ name: "s_4_flower_24", url: "./assets/s_4_flower/24.png" },
	{ name: "s_4_flower_25", url: "./assets/s_4_flower/25.png" },
	{ name: "s_4_tree", url: "./assets/s_4_tree.png" },
	{ name: "s_3_bird", url: "./assets/s_3_bird.png" },
	{ name: "s_4_sign", url: "./assets/s_4_sign.png" },
	{ name: "s_4_2_flower_1", url: "./assets/s_4_flower_2/1.png" },
	{ name: "s_4_2_flower_2", url: "./assets/s_4_flower_2/2.png" },
	{ name: "s_4_2_flower_3", url: "./assets/s_4_flower_2/3.png" },
	{ name: "s_4_2_flower_4", url: "./assets/s_4_flower_2/4.png" },
	{ name: "s_4_2_flower_5", url: "./assets/s_4_flower_2/5.png" },
	{ name: "s_4_2_flower_6", url: "./assets/s_4_flower_2/6.png" },
	{ name: "s_4_2_flower_7", url: "./assets/s_4_flower_2/7.png" },
	{ name: "s_4_2_flower_8", url: "./assets/s_4_flower_2/8.png" },
	{ name: "s_4_2_flower_9", url: "./assets/s_4_flower_2/9.png" },
	{ name: "s_4_2_flower_10", url: "./assets/s_4_flower_2/10.png" },
	{ name: "s_4_2_flower_11", url: "./assets/s_4_flower_2/11.png" },
	{ name: "s_4_2_flower_12", url: "./assets/s_4_flower_2/12.png" },
	{ name: "s_4_2_flower_13", url: "./assets/s_4_flower_2/13.png" },
	{ name: "s_4_2_flower_14", url: "./assets/s_4_flower_2/14.png" },
	{ name: "s_4_2_flower_15", url: "./assets/s_4_flower_2/15.png" },
	{ name: "s_4_2_flower_16", url: "./assets/s_4_flower_2/16.png" },
	{ name: "s_4_2_flower_17", url: "./assets/s_4_flower_2/17.png" },
	{ name: "s_4_2_flower_18", url: "./assets/s_4_flower_2/18.png" },
	{ name: "s_4_2_flower_19", url: "./assets/s_4_flower_2/19.png" },
	{ name: "s_4_2_flower_20", url: "./assets/s_4_flower_2/20.png" },
	{ name: "s_4_2_flower_21", url: "./assets/s_4_flower_2/21.png" },
	{ name: "s_4_2_flower_22", url: "./assets/s_4_flower_2/22.png" },
	{ name: "s_4_2_flower_23", url: "./assets/s_4_flower_2/23.png" },
	{ name: "s_4_2_flower_24", url: "./assets/s_4_flower_2/24.png" },
	{ name: "s_4_2_flower_25", url: "./assets/s_4_flower_2/25.png" },
	{ name: "s_4_smoke_1", url: "./assets/s_4_smoke/1.png" },
	{ name: "s_4_smoke_2", url: "./assets/s_4_smoke/2.png" },
	{ name: "s_4_smoke_3", url: "./assets/s_4_smoke/3.png" },
	{ name: "s_4_smoke_4", url: "./assets/s_4_smoke/4.png" },
	{ name: "s_4_smoke_5", url: "./assets/s_4_smoke/5.png" },
	{ name: "s_4_smoke_6", url: "./assets/s_4_smoke/6.png" },
	{ name: "s_4_smoke_7", url: "./assets/s_4_smoke/7.png" },
	{ name: "s_4_smoke_8", url: "./assets/s_4_smoke/8.png" },
	{ name: "s_4_smoke_9", url: "./assets/s_4_smoke/9.png" },
	{ name: "s_4_smoke_10", url: "./assets/s_4_smoke/10.png" },
	{ name: "s_4_smoke_11", url: "./assets/s_4_smoke/11.png" },
	{ name: "s_4_smoke_12", url: "./assets/s_4_smoke/12.png" },
	{ name: "s_4_smoke_13", url: "./assets/s_4_smoke/13.png" },
	{ name: "s_4_smoke_14", url: "./assets/s_4_smoke/14.png" },
	{ name: "s_4_smoke_15", url: "./assets/s_4_smoke/15.png" },
	{ name: "s_4_smoke_16", url: "./assets/s_4_smoke/16.png" },
	{ name: "s_4_smoke_17", url: "./assets/s_4_smoke/17.png" },
	{ name: "s_4_smoke_18", url: "./assets/s_4_smoke/18.png" },
	{ name: "s_4_smoke_19", url: "./assets/s_4_smoke/19.png" },
	{ name: "s_4_smoke_20", url: "./assets/s_4_smoke/20.png" },
	{ name: "s_4_smoke_21", url: "./assets/s_4_smoke/21.png" },
	{ name: "s_4_smoke_22", url: "./assets/s_4_smoke/22.png" },
	{ name: "s_4_smoke_23", url: "./assets/s_4_smoke/23.png" },
	{ name: "s_4_smoke_24", url: "./assets/s_4_smoke/24.png" },
	{ name: "s_4_smoke_25", url: "./assets/s_4_smoke/25.png" },
	{ name: "s_7_moon", url: "./assets/s_7_moon.png" },
	{ name: "s_7_star", url: "./assets/s_7_star.png" },
	{ name: "s_7_seconds", url: "./assets/s_7_seconds.png" },
	{ name: "s_7_minutes", url: "./assets/s_7_minutes.png" },
	{ name: "s_7_qrcode", url: "./assets/s_7_qrcode.png" },
	{ name: "finger", url: "./assets/finger.png" },
	{ name: "finger1", url: "./assets/finger.png" },
	{ name: "finger2", url: "./assets/finger.png" },
	{ name: "finger3", url: "./assets/finger.png" },
	{ name: "finger6", url: "./assets/finger.png" },
	{ name: "dialog4", url: "./assets/s_4_dialog.png" },
	{ name: "dialog5", url: "./assets/s_5_dialog.png" },
];

const getFrames = (name) => {
	return resource.filter((item) => item.name.indexOf(name) > -1);
};

const container = [
	{
		width: 1624,
		height: 750,
		x: 0,
		y: 0,
		zIndex: 10,
	},
	{
		width: 1624,
		height: 750,
		x: 1624,
		y: 0,
		zIndex: 9,
	},
	{
		width: 1624,
		height: 750,
		x: 3248,
		y: 0,
	},
	{
		width: 1624,
		height: 750,
		x: 4872,
		y: 0,
	},
	{
		width: 1624,
		height: 750,
		x: 6496,
		y: 0,
	},
	{
		width: 1624,
		height: 750,
		x: 8120,
		y: 0,
	},
];

const sprites = [
	{
		index: 0,
		name: "scence_2",
		width: 1624,
		height: 750,
		x: 0,
		y: 0,
	},
	{
		index: 1,
		name: "scence_3",
		width: 1624,
		height: 750,
		x: 0,
		y: 0,
	},
	{
		index: 2,
		name: "scence_4",
		width: 1624,
		height: 750,
		x: 0,
		y: 0,
	},
	{
		index: 3,
		name: "scence_5",
		width: 1624,
		height: 750,
		x: 0,
		y: 0,
	},
	{
		index: 4,
		name: "scence_6",
		width: 1624,
		height: 750,
		x: 0,
		y: 0,
	},
	{
		index: 5,
		name: "scence_7",
		width: 1624,
		height: 750,
		x: 0,
		y: 0,
	},
	{
		index: 0,
		name: "tip01",
		width: 160,
		height: 44,
		alpha: 0,
		x: 10,
		y: 600,
	},
	{
		index: 0,
		name: "bear",
		width: 362 / 4,
		height: 506 / 4,
		x: 600,
		y: 400,
	},
	{
		index: 0,
		name: "s_2_cloud",
		width: 308,
		height: 72,
		x: 1250,
		y: 30,
	},
	{
		index: 1,
		name: "bike1",
		width: 752,
		height: 634,
		x: 100,
		y: 30,
	},
	{
		index: 1,
		name: "s_2_tree",
		width: 322,
		height: 249,
		x: -300,
		y: 500,
		zIndex: 10,
	},
	{
		index: 1,
		name: "dialog3",
		width: 387,
		height: 119,
		x: 340,
		y: 240,
		interactive: true,
		events: {
			name: "pointertap",
			fn: (cb) => {
				if (typeof cb === "function") {
					cb();
				}
			},
		},
	},
	{
		index: 2,
		name: "dialog4",
		width: 357,
		height: 119,
		x: 440,
		y: 240,
		interactive: true,
		events: {
			name: "pointertap",
			fn: (cb) => {
				if (typeof cb === "function") {
					cb();
				}
			},
		},
	},
	{
		index: 3,
		name: "dialog5",
		width: 381,
		height: 119,
		x: 380,
		y: 220,
		interactive: true,
		events: {
			name: "pointertap",
			fn: (cb) => {
				if (typeof cb === "function") {
					cb();
				}
			},
		},
	},
	{
		index: 2,
		name: "s_3_tree",
		width: 1750,
		height: 750,
		x: -1300,
		y: 0,
		zIndex: 10,
	},
	{
		index: 2,
		name: "s_3_bird",
		width: 1009,
		height: 243,
		x: 480,
		y: -60,
		zIndex: 8,
	},
	{
		index: 3,
		name: "s_4_tree",
		width: 1156,
		height: 734,
		x: -700,
		y: 0,
		zIndex: 10,
	},
	{
		index: 3,
		name: "s_4_sign",
		width: 363,
		height: 179,
		x: 300,
		y: 450,
		scale: {
			x: 0.5,
			y: 0.5,
		},
		zIndex: 10,
	},
	{
		index: 0,
		name: "dialog2",
		width: 412,
		height: 119,
		x: 900,
		y: 200,
		interactive: true,
		events: {
			name: "pointertap",
			fn: (cb) => {
				if (typeof cb === "function") {
					cb();
				}
			},
		},
	},
	{
		index: 0,
		name: "finger",
		width: 99,
		height: 95,
		x: 1200,
		y: 350,
		alpha: 0,
		scale: {
			x: 0.5,
			y: 0.5,
		},
	},
	{
		index: 1,
		name: "finger1",
		width: 99,
		height: 95,
		x: 600,
		y: 370,
		alpha: 0,
		scale: {
			x: 0.5,
			y: 0.5,
		},
	},
	{
		index: 2,
		name: "finger2",
		width: 99,
		height: 95,
		x: 660,
		y: 370,
		alpha: 0,
		scale: {
			x: 0.5,
			y: 0.5,
		},
	},
	{
		index: 3,
		name: "finger3",
		width: 99,
		height: 95,
		x: 660,
		y: 360,
		alpha: 0,
		scale: {
			x: 0.5,
			y: 0.5,
		},
	},
	{
		index: 4,
		name: "finger6",
		width: 99,
		height: 95,
		x: 1000,
		y: 430,
		alpha: 0,
		scale: {
			x: 0.5,
			y: 0.5,
		},
		zIndex: 10,
	},
	{
		index: 4,
		name: "car",
		width: 135,
		height: 93,
		x: 700,
		y: 600,
	},
	{
		index: 4,
		name: "win",
		width: 113,
		height: 182,
		x: 1370,
		y: 90,
	},
	{
		index: 4,
		name: "s_6_cloud",
		width: 78,
		height: 23,
		x: 1450,
		y: 105,
	},
	{
		index: 5,
		name: "win_right",
		width: 116,
		height: 182,
		x: 120,
		y: 90,
		anchor: {
			x: 1,
			y: 0,
		},
		zIndex: 10,
	},
	{
		index: 5,
		name: "s_7_moon",
		width: 292,
		height: 186,
		x: 980,
		y: 10,
	},
	{
		index: 5,
		name: "s_7_star",
		width: 245,
		height: 199,
		x: 980,
		y: 40,
	},
	{
		index: 5,
		name: "s_7_seconds",
		width: 23,
		height: 5,
		x: 1475,
		y: 100,
	},
	{
		index: 5,
		name: "s_7_minutes",
		width: 9,
		height: 30,
		x: 1503,
		y: 102,
	},
	{
		index: 5,
		name: "s_7_qrcode",
		width: 279,
		height: 315,
		x: 455,
		y: 52,
		interactive: true,
		events: {
			name: "pointertap",
			fn: (cb) => {
				if (typeof cb === "function") {
					cb();
				}
			},
		},
	},
	{
		index: 4,
		name: "dialog6",
		width: 361,
		height: 138,
		x: 740,
		y: 280,
		interactive: true,
		events: {
			name: "pointertap",
			fn: (cb) => {
				if (typeof cb === "function") {
					cb();
				}
			},
		},
	},
];

const animatedSprites = [
	{
		index: 1,
		name: "s_2_flower_1",
		width: 350,
		height: 150,
		x: -390,
		y: 620,
		zIndex: 11,
		frames: getFrames("s_2_flower_"),
	},
	{
		index: 1,
		name: "s_2_2_flower_1",
		width: 300,
		height: 300,
		x: -80,
		y: 500,
		zIndex: 11,
		frames: getFrames("s_2_2_flower_"),
	},
	{
		index: 1,
		name: "s_3_flower_1",
		width: 800,
		height: 300,
		x: -40,
		y: 480,
		zIndex: 10,
		frames: getFrames("s_3_flower_"),
	},
	{
		index: 2,
		name: "s_3_2_flower_1",
		width: 550,
		height: 200,
		x: -500,
		y: 580,
		zIndex: 11,
		frames: getFrames("s_3_2_flower_"),
	},
	{
		index: 3,
		name: "s_4_flower_1",
		width: 550,
		height: 250,
		x: -360,
		y: 500,
		zIndex: 11,
		frames: getFrames("s_4_flower_"),
	},
	{
		index: 3,
		name: "s_4_2_flower_1",
		width: 280,
		height: 180,
		x: 160,
		y: 530,
		zIndex: 11,
		frames: getFrames("s_4_2_flower_"),
	},
	{
		index: 3,
		name: "s_4_smoke_1",
		width: 280,
		height: 180,
		x: 1240,
		y: -70,
		zIndex: 11,
		frames: getFrames("s_4_smoke_"),
	},
];

const animations = {
	tip01: {
		prop: "delay",
		name: "tip01",
		duration: 1,
		delay: 0,
		option: {
			alpha: 1,
			yoyo: true,
			repeat: -1,
			ease: Power0.easeNone,
		},
	},
	bear: {
		prop: "to",
		name: "bear",
		duration: 0.1,
		delay: 0,
		option: {
			width: 362,
			height: 506,
			x: 500,
			y: 280,
			ease: Power0.easeNone,
		},
	},
	s_2_cloud: {
		prop: "to",
		name: "s_2_cloud",
		duration: 0.1,
		delay: 0,
		option: {
			x: 1200,
			y: 100,
			ease: Power0.easeNone,
		},
	},
	bike1: {
		prop: "from",
		name: "bike1",
		duration: 0.2,
		delay: 0.15,
		frames: getFrames("bike"),
		option: {
			x: 1200,
			ease: Power0.easeNone,
		},
	},
	dialog2: {
		prop: "from",
		duration: 0.01,
		delay: 0.05,
		option: {
			alpha: 0,
			ease: Power0.easeIn,
		},
	},
	finger: {
		prop: "to",
		duration: 0.01,
		delay: 0.05,
		option: {
			alpha: 1,
			ease: Power0.easeIn,
		},
		scale: {
			x: 1,
			y: 1,
			duration: 0.1,
			repeat: -1,
			yoyo: true,
		},
		auto: true,
	},
	finger1: {
		prop: "to",
		duration: 0.01,
		delay: 0.2,
		option: {
			alpha: 1,
			ease: Power0.easeIn,
		},
		scale: {
			x: 1,
			y: 1,
			duration: 0.1,
			repeat: -1,
			yoyo: true,
		},
		auto: true,
	},
	finger2: {
		prop: "to",
		duration: 0.01,
		delay: 0.35,
		option: {
			alpha: 1,
			ease: Power0.easeIn,
		},
		scale: {
			x: 1,
			y: 1,
			duration: 0.1,
			repeat: -1,
			yoyo: true,
		},
		auto: true,
	},
	finger3: {
		prop: "to",
		duration: 0.01,
		delay: 0.5,
		option: {
			alpha: 1,
			ease: Power0.easeIn,
		},
		scale: {
			x: 1,
			y: 1,
			duration: 0.1,
			repeat: -1,
			yoyo: true,
		},
		auto: true,
	},
	finger6: {
		prop: "to",
		duration: 0.01,
		delay: 0.8,
		option: {
			alpha: 1,
			ease: Power0.easeIn,
		},
		scale: {
			x: 1,
			y: 1,
			duration: 0.1,
			repeat: -1,
			yoyo: true,
		},
		auto: true,
	},
	s_3_bird: {
		prop: "to",
		duration: 0.1,
		delay: 0.4,
		option: {
			x: 120,
			y: -80,
			alpha: 0,
			ease: Power0.easeIn,
		},
	},
	s_4_sign: {
		prop: "to",
		duration: 0.1,
		delay: 0.5,
		option: {
			ease: Power0.easeIn,
		},
		scale: {
			x: 1,
			y: 1,
		},
	},
	dialog3: {
		prop: "from",
		duration: 0.01,
		delay: 0.2,
		option: {
			alpha: 0,
			ease: Power0.easeIn,
		},
	},
	dialog4: {
		prop: "from",
		duration: 0.01,
		delay: 0.35,
		option: {
			alpha: 0,
			ease: Power0.easeIn,
		},
	},
	dialog5: {
		prop: "from",
		duration: 0.01,
		delay: 0.5,
		option: {
			alpha: 0,
			ease: Power0.easeIn,
		},
	},
	car: {
		prop: "to",
		duration: 0.1,
		delay: 0.8,
		option: {
			x: 950,
			ease: Power0.easeNone,
		},
	},
	win: {
		prop: "to",
		duration: 0.1,
		delay: 0.8,
		option: {
			width: 43,
			ease: Power0.easeNone,
		},
	},
	s_6_cloud: {
		prop: "auto",
		duration: 2,
		delay: 0.8,
		option: {
			x: 1500,
			alpha: 0,
			repeat: -1,
			yoyo: 1,
			ease: Power0.easeNone,
		},
	},
	s_7_moon: {
		prop: "auto",
		duration: 2,
		delay: 0.8,
		option: {
			y: 0,
			alpha: 0.3,
			repeat: -1,
			yoyo: 1,
			ease: Power0.easeNone,
		},
	},
	s_7_star: {
		prop: "auto",
		duration: 1,
		delay: 0.8,
		option: {
			alpha: 0.5,
			repeat: -1,
			yoyo: 1,
			ease: Power0.easeNone,
		},
	},
	s_7_minutes: {
		prop: "auto",
		duration: 60,
		delay: 0.8,
		option: {
			rotation: 180,
			repeat: -1,
			yoyo: 1,
			ease: Power0.easeNone,
		},
	},
	win_right: {
		prop: "to",
		duration: 0.1,
		delay: 0.8,
		option: {
			width: 43,
			ease: Power0.easeNone,
		},
	},
	dialog6: {
		prop: "from",
		duration: 0.01,
		delay: 0.8,
		option: {
			alpha: 0,
			ease: Power0.easeIn,
		},
	},
};

export { resource, container, sprites, animations, animatedSprites };
